import styles from '../styles/Home.module.css'
import Buttons from '../components/Buttons/Buttons.jsx'
import Form from '../components/Form/Form.jsx'
import Head from 'next/head'
import Script from 'next/script'


export default function Home() {
  return (
    <div id="top-image">
      <div className={styles.container}>
        <Head>
          <title>Pokédex</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-16x16.png" />

        </Head>

        <main className={styles.main}>

          <img className={styles.logo} src="/images/pokedex-logo.png" alt="Pokédex!" width={250} height={90}>
          </img >
          <img className={styles.pokemon__img} src="" id="pokemon__img" alt="pokedex" width={150} height={150}></img>
          <img className={styles.pokedex} src="/images/pokedex.png" alt="Pokédex!" width={549} height={423}></img>

          <h1 className={styles.pokemon__data}>
            <span className={styles.pokemon__number} id="pokemon__number"></span> -
            <span className={styles.pokemon__name} id="pokemon__name"></span>
            <span className={styles.pokemon__type} id="pokemon__type"></span>
          </h1>



          <Form />

          <Buttons />

          <Script src='/pokemons.js' />

        </main>

      </div>
    </div>
  )
}

